#include "app_shared.h"

AppSettingsServo appSettingsServo = {15, 45, 75, 105, 135, 165};
AppSettingsDosage appSettingsDodage = {100, 100, 100, 100, 100, 100};
AppSettings appSettings = {appSettingsServo, 5000, appSettingsDodage};

const MenuItem menuServo[] = {
    {
        "Рюмка 1",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.servo.r1,
        0,
        180,
        &menuCalibration[0],
    },
    {
        "Рюмка 2",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.servo.r2,
        0,
        180,
        &menuCalibration[0],
    },
    {
        "Рюмка 3",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.servo.r3,
        0,
        180,
        &menuCalibration[0],
    },
    {
        "Рюмка 4",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.servo.r4,
        0,
        180,
        &menuCalibration[0],
    },
    {
        "Рюмка 5",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.servo.r5,
        0,
        180,
        &menuCalibration[0],
    },
    {
        "Рюмка 6",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.servo.r6,
        0,
        180,
        &menuCalibration[0],
    },
};

const MenuItem menuDosage[] = {
    {
        "Рюмка 1",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.dosage.r1,
        0,
        100,
        &menuCalibration[2],
    },
    {
        "Рюмка 2",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.dosage.r2,
        0,
        100,
        &menuCalibration[2],
    },
    {
        "Рюмка 3",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.dosage.r3,
        0,
        100,
        &menuCalibration[2],
    },
    {
        "Рюмка 4",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.dosage.r4,
        0,
        100,
        &menuCalibration[2],
    },
    {
        "Рюмка 5",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.dosage.r5,
        0,
        100,
        &menuCalibration[2],
    },
    {
        "Рюмка 6",
        MenuItemType::Settings,
        nullptr,
        0,
        (int *)&appSettings.dosage.r6,
        0,
        100,
        &menuCalibration[2],
    },
};

const MenuItem menuCalibration[3] = {
    {
        "Дозы по рюмкам",
        MenuItemType::Menu,
        menuDosage,
        6,
        nullptr,
        0,
        0,
        &mainMenu,
    },
    {
        "Нaстройка серво",
        MenuItemType::Menu,
        menuServo,
        6,
        nullptr,
        0,
        0,
        &mainMenu,
    },
    {
        "Сколько льем",
        MenuItemType::Action,
        nullptr,
        0,
        nullptr,
        0,
        0,
        &mainMenu,
    },
};

const MenuItem mainMenu = {
    "Калибровка", MenuItemType::Menu, menuCalibration, 3, nullptr, 0, 0,
    nullptr,
};
